### ISSUE TITLE
Not reporting any bans

### ISSUE THREAD

**Issue by drewfatstacks** [IceQ1337/SteamBanChecker_Discord#1]
I am able to get the script to run, add accounts, it pulls the data from Steam, judging by the data in the profiles.db.  I added three accounts, one normal, one VAC banned and one game banned.  It is reporting that all 3 are clean.  But in the profiles.db it shows then banned.  

> "VACBanned":true,"NumberOfVACBans":1 - on the VAC'd account
> "NumberOfGameBans":1 - on the gamebanned account.

But when I call !stats on the bot it reports 

> Steam Ban Checker Statistics
>Total Profiles
>3
>Banned Profiles
>0
>Percentage
>0%

Any insight would be helpful.  I thought about trying the Telegram version as it was more recently updated, but I do not use Telegram.

Thanks!

**Comment by IceQ1337** [comment]
The program is not intended to just check profiles for bans. Adding banned profiles to the SteamBanChecker does not make sense, because both scripts (discord & telegram) are designed to be notified about new bans. If you add a profile that is already banned, it will only send you a notification if it gets banned once more.

In order to check if this is working properly, you can edit the information of a banned profile in the `profiles.db` file. Make sure that the following fields are set corretly: `"Tracked": true`, `"VACBanned": false`, `"NumberOfVACBans": 0` and `"NumberOfGameBans": 0`. If you then run the script, you will receive a notification.
