### ISSUE TITLE
Error when sending to discord

### ISSUE THREAD

**Issue by guiiicd** [IceQ1337/SteamBanChecker_Discord#11]
I'm using the array of multiple channels method and when I leave the `"botChannelOutput": "",` and it's giving this error when someone is banned
![image](https://user-images.githubusercontent.com/24928611/99210452-34d9c300-279c-11eb-91ad-7ab678043739.png)

My config.json:
![image](https://user-images.githubusercontent.com/24928611/99210609-a3b71c00-279c-11eb-9219-7bda50b9023b.png)

Error code:
```[Mon, 16 Nov 2020 03:39:23 GMT] [ERROR] [Screenshot] saveProfile > TypeError: Cannot read property 'send' of undefined
(node:595) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
at module.exports.sendMessage (/app/modules/Discord.js:89:55)
at /app/server.js:135:25
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by IceQ1337** [comment]
Hello @FPSGuilherme 
The bot usually only allows one output channel, and if it is not set, the input channel is used. However, this will not work if multiple input channels are used, so it will result in a crash. I will provide an update that takes multiple input channels into account.

**Comment by IceQ1337** [comment]
You can now specify multiple output channels. If you do not specify any output channels, the bot will now also take multiple input channels into account. A downside of this is that messages are sent to all input channels and not just to the one where the profile was checked. Due to the structure of the bot, however, this is a change that I currently don't have time for. I hope your problem is solved and you are fine with the current solution for now.

If you don't want to download the whole repository, you can just replace the following file: `modules/Discord.js`
Please tell me if you still receive an error.

**Comment by guiiicd** [comment]
No problem, I will test and answer here. Thanks!

**Comment by IceQ1337** [comment]
It seems the changes fixed the issue, so I'll close the issue.
