### ISSUE TITLE
[ERROR] [Discord] sendMessage > AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by ROCKSTARoc** [IceQ1337/SteamBanChecker_Discord#13]
New instance got this error:

[ERROR] [Discord] sendMessage > AbortError: The user aborted a request.

**Comment by IceQ1337** [comment]
Hello @ROCKSTARoc 
This error is not caused by the script and can be ignored. The problem is likely with your or the servers internet connection, which may prevent notifications from being sent. It could also be that you are using the bot in other places, which results in a rate limitation. See https://github.com/discordjs/discord.js/issues/3471 and https://github.com/discordjs/discord.js/pull/4852 for more information. Please make sure you download a fresh copy of this repository or `npm update` regularily in order to always be up-to-date.

**Comment by ROCKSTARoc** [comment]
Yeah fixed before with your tipps. Thanks! But i have more issue.
I open a new one.

**Comment by Bobby8904** [comment]
still having the issue after doing npm update any suggestions also I don't run bot anywhere else except on one server.
