### ISSUE TITLE
[ERROR] [Discord] sendMessage > AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by Bobby8904** [IceQ1337/SteamBanChecker_Discord#18]
How can i fix this? Doesnt want to mention in discord...

**Comment by IceQ1337** [comment]
Please see https://github.com/IceQ1337/SteamBanChecker_Discord/issues/13

Since the error isn't caused by the script directly and i currently don't have enough time to see if i can improve on anything, there is nothing i can do but to advise updating anything (script, nodejs, etc.) to the latest version and to not use multiple bot instances at the same time.

**Comment by Bobby8904** [comment]
Alright i noticed after i did the update command it updated stuff so hopefully that fixed it...

**Comment by IceQ1337** [comment]
@Bobby8904
What exact messages are affected by this error and how often does this error occur? Also, could it be that this error only occurs on ban messages? If so, do you have screenshots enabled and can you please try to disable screenshots if you do?

**Comment by Bobby8904** [comment]
Yeah only happens when someone gets banned Uhm so the screenshot function is broken damn alright ill disable it and if someone gets banned ill let you know if I still get the error.

**Comment by Bobby8904** [comment]
I checked in datastore and screenshots does appear there but doesn't send to discord ill disable send screenshots to discord and see if then no errors occur hopefully it can be fixed tho would be nice to see screenshots

**Comment by IceQ1337** [comment]
Yeah, there may be problems sending the screenshots, e.g. that it takes too long, which then aborts the action.  
Let me know if it works without screenshots and if it does, I may be able to find a workaround for the problem :)

**Comment by ROCKSTARoc** [comment]
I got this error in #13.
Dont know why but with a new VPS ip it works ;)

**Comment by IceQ1337** [comment]
Then the VPS connection was probably the problem. I'm glad it works now :)

**Comment by Bobby8904** [comment]
> Yeah, there may be problems sending the screenshots, e.g. that it takes too long, which then aborts the action.
> Let me know if it works without screenshots and if it does, I may be able to find a workaround for the problem :)

Yup, you are right it works when I disable send screenshots in cfg. (but still would be clean if it could work)

**Comment by Bobby8904** [comment]
Would also be helpful if there was a command for testing like /test or so to see if it works.

**Comment by IceQ1337** [comment]
> Yup, you are right it works when I disable send screenshots in cfg. (but still would be clean if it could work)

It has something to do with your VPS not being able to send/upload the screenshot fast enough due to its internet connection. There is nothing i can do about it. For others, sending screenshots works totally fine.

> Would also be helpful if there was a command for testing like /test or so to see if it works.

I don't think this is necessary. If you want to force ban messages, you can always add a banned account and manipulate its saved data (number of bans and checked status) in the `profiles.db` so it gets checked and reported again.
