### ISSUE TITLE
adding more than one channel as an Input

### ISSUE THREAD

**Issue by pelasta** [IceQ1337/SteamBanChecker_Discord#2]
is it possible to add more than a channel in the config as an input?

**Comment by IceQ1337** [comment]
No, this is not possible by default.

You would need to implement a different check in the [discord.js](https://github.com/IceQ1337/SteamBanChecker_Discord/blob/master/modules/Discord.js#L35) file in order to then use an array of IDs in the [config file](https://github.com/IceQ1337/SteamBanChecker_Discord/blob/master/configs/config.json.example#L10).

`channelID != Config.Discord.botChannelInput`=> `!Config.Discord.botChannelInput.includes(channelID)`
`"botChannelInput": "DISCORD CHANNEL ID",` => `"botChannelInput": ["CHANNEL ID 1", "CHANNEL ID 2"],`

**Comment by Borlax2** [comment]
can you please add this as an option?

**Comment by IceQ1337** [comment]
> can you please add this as an option? it should have been included in the last update you just released

Excuse me if I misinterpret the second part of your sentence, but why exactly "should that have been in the last update"? I didn't mention anywhere that I intend to implement this and in my answer above, I've literally posted all the necessary code to implement this. If you'd just suggested it again, I probably would have made a change to this, but now I don't want to do that anytime soon.

I'm always happy to help people, but people like you, who always want everything but never want to do anything for it and take everything for granted, really go against my grain. Maybe you should read through what GitHub is all about.

**Comment by Borlax2** [comment]
Definitely misinterpret what I meant to say, but since your reply was so mean, it's fine though no need to be bitch about it, just don't do it who the fuck cares? your project(s) are trash anyways and I haven't even used...

**Comment by IceQ1337** [comment]
Implemented in https://github.com/IceQ1337/SteamBanChecker_Discord/commit/7ae4f853d63ecc2f881079d9b925c8dc42aaad2c.

@Borlax2 has been permanenlty blocked because I don't need such people in my projects.
